name: PPX

on: [push]

jobs:
  ppx:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    name: PPX
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: packages/rescript-relay/rescript-relay-ppx
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.19.0
        env:
          CI: true
      - name: Install esy
        run: npm install -g esy
      - name: Build PPX
        uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-v1
          working-directory: packages/rescript-relay/rescript-relay-ppx
      - name: Test PPX
        run: esy test
      - name: Copy built PPX file
        run: |
          mv ./_esy/default/build/default/bin/RescriptRelayPpxApp.exe ${{ fromJson('{ "ubuntu-latest": "ppx-linux", "macos-latest": "ppx-darwin" }')[matrix.platform] }}
      - name: Upload PPX artifact
        uses: actions/upload-artifact@v2
        with:
          name: ppx-${{ matrix.platform }}
          path: packages/rescript-relay/rescript-relay-ppx/ppx-*
          if-no-files-found: error
